--DROP TABLE IF EXISTS ACCOUNT;
--DROP TABLE IF EXISTS CLIENT;

CREATE SCHEMA IF NOT EXISTS PUBLIC;
CREATE TABLE IF NOT EXISTS PUBLIC.CLIENT (
	LAST_NAME CHARACTER VARYING NOT NULL,
	FIRST_NAME CHARACTER VARYING NOT NULL,
    MIDDLE_NAME CHARACTER VARYING NOT NULL,
    PHONE_NUMBER LONG NOT NULL PRIMARY KEY,
	INN CHARACTER VARYING NOT NULL,
	ADDRESS CHARACTER VARYING NOT NULL
);

CREATE TABLE IF NOT EXISTS PUBLIC.ACCOUNT (
	NUMBER LONG NOT NULL PRIMARY KEY,
	BALANCE LONG NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    BIK LONG NOT NULL,
	CURRENCY CHARACTER VARYING NOT NULL,
	CLIENT_PHONE_NUMBER LONG NOT NULL,
	CONSTRAINT ACCOUNT_FK FOREIGN KEY (CLIENT_PHONE_NUMBER) REFERENCES CLIENT(PHONE_NUMBER)
);